### ISSUE TITLE
Self-hosted Send files cannot be downloaded

### ISSUE THREAD

**Issue by dlrudie** [bitwarden/server#1367]
## Describe the Bug

Self-hosted Send files cannot be downloaded.

## Steps To Reproduce

1. Create a new send to share a file.
2. Open link to the file.
3. Click download.
4. The button will change to a spinning icon but nothing happens.

## Expected Result

File should download.

## Actual Result

File does not download.

## Screenshots or Videos

N/A

## Environment

- Operating system: Ubuntu 18.04.5 LTS
- Build Version: 1.41.3
- Self Hosted: true
- Environment: Cloud
- Hardware: Hosted VPS

## Additional Context

Doing some digging through various logs led to nothing.
After browsing the bwdata directory I stumbled upon something that may or may not have anything to do with the problem.
In _~/bwdata/core_ I see two directories. One is named _**attachments**_ while the other is named _**attchments**_. The file I uploaded is stored within _attchments_ while the _attachments_ directory is empty. In _~/bwdata/nginx/default.conf_ the location there points to _attachments_.
I see that in server/src/Core/Settings/GlobalSettings.cs on lines 13 and 14 it mentions _attchments_.
I don't know if this is intentional, by design, or a typo.

**Comment by dlrudie** [comment]
Opened inspector in the browser and see some errors pop up as soon as you click downloads. So it probably isn't related to the directory layout I mentioned above.

![Untitled](https://user-images.githubusercontent.com/1780069/120120195-5bbc7d00-c161-11eb-9b8a-66ecd9aa592f.png)

**Comment by c4539** [comment]
Have you checked you ./`bwdata/env/global.override.env` for these entries?

```
globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__attachment__baseUrl=https://vault.example.net/attachments
globalSettings__send__baseDirectory=/etc/bitwarden/core/attachments/send
globalSettings__send__baseUrl=https://vault.example.net/attachments/send
```
That should override the typo you found in `server/src/Core/Settings/GlobalSettings.cs`.

**Comment by Virinum** [comment]
I have the same problem so I tried setting these entries:

```
globalSettings__attachment__baseDirectory=/etc/bitwarden/bwdata/core/attachments
globalSettings__attachment__baseUrl=https://bitwarden.XXXX.de/attachments
globalSettings__send__baseDirectory=/etc/bitwarden/bwdata/core/attachments/send
globalSettings__send__baseUrl=https://bitwarden.XXXX.de/attachments/send
```

First thing I noticed after uploading a file was that no attachment and no send file appears in `/etc/bitwarden/bwdata/core/attachments` or `/etc/bitwarden/bwdata/core/attachments/send`. I couldn't find theme anywhere.

When I try to download a file this error pops up:
![image](https://user-images.githubusercontent.com/42373861/120381241-78ec7980-c322-11eb-9268-ba35e6b24fe7.png)

By the way - are these variables documented somewhere? I just found [this](https://bitwarden.com/help/article/environment-variables/) and [this](https://bitwarden.com/help/article/send-hosting/).

**Comment by dlrudie** [comment]
@c4539 Thanks for giving me an idea where to start looking around.

I added the lines to my global override file and adjusted the paths accordingly.

It still doesn't appear to work. Now as soon as I click Save it logs me out instantly. The errors in the inspector are 401 which has to do with authorization. The file never gets saved. I triple-checked the paths I added and they are correct. Permissions on the directories are also correct.

There is a CSP error at the bottom that appears even before I hit save so I'm not sure if that's the whole cause of the problem either.

```
globalSettings__baseServiceUri__vault=https://site.org
globalSettings__sqlServer__connectionString="Data Source=tcp:mssql,1433;Initial Catalog=vault;Persist Security Info=False;User ID=sa;Password=...;MultipleActiveResultSets=False;Connect Timeout=30;Encrypt=True;TrustServerCertificate=True"
globalSettings__identityServer__certificatePassword=...
globalSettings__internalIdentityKey=...
globalSettings__oidcIdentityClientKey=...
globalSettings__duo__aKey=...
globalSettings__installation__id=...
globalSettings__installation__key=...
globalSettings__mail__replyToEmail=no-reply@site.org
globalSettings__mail__smtp__host=smtp.gmail.com
globalSettings__mail__smtp__port=587
globalSettings__mail__smtp__ssl=true
globalSettings__mail__smtp__username=no-reply@site.org
globalSettings__mail__smtp__password=...
globalSettings__disableUserRegistration=false
adminSettings__admins=...
globalSettings__attachment__baseDirectory=/root/bwdata/core/attachments
globalSettings__attachment__baseUrl=https://site.org/attachments
globalSettings__send__baseDirectory=/root/bwdata/core/attachments/send
globalSettings__send__baseUrl=https://site.org/attachments/send
```


![image](https://user-images.githubusercontent.com/1780069/120387225-3bbac400-c2ef-11eb-915c-8bf84a35fe65.png)


![image](https://user-images.githubusercontent.com/1780069/120387562-b257c180-c2ef-11eb-8fb4-39f9e42573da.png)

**Comment by Virinum** [comment]
I got it working with these settings:

```
globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__attachment__baseUrl=https://bitwarden.XXXX.de/attachments
globalSettings__send__baseDirectory=/etc/bitwarden/bwdata/core/attachments/send
globalSettings__send__baseUrl=https://bitwarden.XXXX.de/attachments/send
```

Don't change `globalSettings__attachment__baseDirectory` and `globalSettings__send__baseDirectory`. You just need to adjust `globalSettings__attachment__baseUrl` and `globalSettings__send__baseUrl`.

`globalSettings__attachment__baseDirectory` and `globalSettings__send__baseDirectory` are the paths inside the docker container.

So your paths must start with `/etc/bitwarden/core` because this volume gets mapped to `../core` (see `docker-compose.yml`)

**Comment by dlrudie** [comment]
They don't have to start with /etc/bitwarden/*. In docker-compose.yml it specificies either "../core/attachments" or "/etc/bitwarden/core/attachments". I don't have a /etc/bitwarden at all. Everything is contained within /root/bwdata and the rest of the directories work just fine.

The ../core/attachments is valid on mine. I think my problem comes from the fact that the source has a typo for the directory and it's messing with everything else. The URL's are fine on mine and I don't see any reason to change the baseUrl settings.

If I don't add those four lines, whenever I create a file send it will end up in bwdata/core/attchments with the typo. I can delete the send and it will properly delete the file too. I just can't download it. I've tried renaming bwdata/core/attachments and creating a symlink in its place that points to attchments but it still didn't work.

**Comment by Virinum** [comment]
> In docker-compose.yml it specificies either "../core/attachments" or "/etc/bitwarden/core/attachments".

You are talking about this line in `docker-compose.yml`, right?
`../core/attachments:/etc/bitwarden/core/attachments`

`../core/attachments` is the source path on your host relative to your `docker-compose.yml` (so in your case it's `/root/bwdata/core/attachments`)
`/etc/bitwarden/core/attachments` is the target path inside the docker container

So you do have `/etc/bitwarden`, but only inside your containers (it's like a separate virtual linux host).

The only thing you can change with `globalSettings__attachment__baseDirectory` and `globalSettings__send__baseUrl` is the path where it gets mounted inside your docker container. Which doesn't make much sense for me. But because there is this typo, you have to set this.

**Comment by dlrudie** [comment]
Okay, that makes sense on that. I tried setting the /etc/bitwarden/core/attachments and send one in the global override but it still doesn't work for downloads.

As soon as I click the download button I get the same javascript error as in my original screenshot.

"Refused to connect to 'http://localhost:4000/sendfiles//.../...' because it violates the following Content Security Policy directive: "connect-src 'self' wss://site.com https://api.pwnedpasswords.com https://2fa.directory".

**Comment by Virinum** [comment]
I had the same error message. But setting these entries fixed it for me:

```
globalSettings__attachment__baseUrl=https://bitwarden.XXXX.de/attachments
globalSettings__send__baseUrl=https://bitwarden.XXXX.de/attachments/send
```

**Comment by dlrudie** [comment]
Thanks. That worked now.
So for mine to work it really needed all four of those lines as @c4539 called out.

globalSettings__attachment__baseDirectory=/etc/bitwarden/core/attachments
globalSettings__attachment__baseUrl=https://site.com/attachments
globalSettings__send__baseDirectory=/etc/bitwarden/core/attachments/send
globalSettings__send__baseUrl=https://site.com/attachments/send

I just got confused about the /etc/bitwarden path and was trying to change it to /root/bwdata instead.

Will these settings be future-proof or if the typo gets fixed in the source will I need to undo these?

Thanks, @c4539 @Virinum

**Comment by Virinum** [comment]
As far as I can tell from looking at the code, you can remove `globalSettings__attachment__baseDirectory` and `globalSettings__send__baseDirectory` once my pull request (#1374) gets merged and the new release is deployed on your server.
But keeping these entries shouldn't have any disadvantages.

**Comment by cscharf** [comment]
It turns out this typo occurred during a larger refactor, #1263. #1374 should resolve this issue and we'll be testing it internally here soon for a possible patch/hot-fix release.

Our self-hosted testbed internally is a long-lived instance and at some point someone added those keys to its config and we missed an opportunity to document or investigate an issue there during our regression testing (which is why this issue has not been reproducible and wasn't caught during testing). We'll be expanding our regression suite to include standing up a "fresh" self-hosted instance for each server release going forward.

**Comment by MarjobIf** [comment]
An update has largely resolved this problem. But I noticed that a send still doesn't work when using domain redirects.

Our self-hosted instance runs, for example, via bitwarden.**hetzner**.firmname.com and we also forward to it from bitwarden.firmname.com (CNAME).

The download of a send created by bitwarden.firmname.com does not work, whereas a send from bitwarden.**hetzner**.firmname.com works.

The sends use a correspondingly different link:

https://bitwarden.**hetzner**.firmname.com/#/send/W9S8vYs0-_061gAH3LAg3nG0ebLs5Fq-Ru2p7Aw -> working

https://bitwarden.firmname.com/#/send/W9S8vYs0-_061gAH3LAg3nG0ebLs5Fq-Ru2p7Aw -> not working

**Comment by eliykat** [comment]
Hi @MarjobIf, please open a new issue for the problem you're experiencing - I think it's different enough that I don't want to reopen this thread.

**Comment by Mart124** [comment]
_This could be closed, as solved by the last server version._
