### ISSUE TITLE
Web Installed: Unable to fetch installed version

### ISSUE THREAD

**Issue by GieltjE** [bitwarden/server#2530]
### Steps To Reproduce

1: install on localhost using docker
2: log into the /admin panel

### Expected Result

"Web Installed" displays "Unable to fetch installed version"

### Actual Result

"Web Installed" displays a version or if no longer applicable.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/2291132/210171935-17f22a9b-e42d-44bb-8808-94c05c451743.png)

### Githash Version

455d62e-dirty

### Environment Details

- OS: Win 11 insider
- Env: Docker
- Hardware: 3700X 64GB ram

### Database Image

Mariadb: 10.10.2

### Issue-Link

https://github.com/bitwarden/server/issues/2480

### Issue Tracking Info

- [X] I understand that work is tracked outside of Github. A PR will be linked to this issue should one be opened to address it, but Bitwarden doesn't use fields like "assigned", "milestone", or "project" to track progress.

**Comment by kspearrin** [comment]
Is your localhost instance available under https?

**Comment by kspearrin** [comment]
If you look at the developer console, I imagine you will see something about blocking http/s requests from a non-http source.

**Comment by GieltjE** [comment]
No, http://localhost/admin/home/getinstalledwebversion which responds with http 500 and "Unable to fetch installed version"

**Comment by GieltjE** [comment]
```
      => SpanId:c7c9437910026af0, TraceId:db90bc508bd7ec3167e1da8e640f937e, ParentId:0000000000000000 => ConnectionId:0HMNGJHNF5H2U => RequestPath:/admin/home/getinstalledwebversion RequestId:0HMNGJHNF5H2U:00000002 => Bit.Admin.Controllers.HomeController.GetInstalledWebVersion (Admin)
      Error encountered while sending GET request to http://localhost:80/version.json
      System.Net.Http.HttpRequestException: Address not available (localhost:80)
       ---> System.Net.Sockets.SocketException (99): Address not available
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
         at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
         at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Bit.Admin.Controllers.HomeController.GetInstalledWebVersion(CancellationToken cancellationToken) in /source/src/Admin/Controllers/HomeController.cs:line 73
```

**Comment by bkirkland13** [comment]
I am seeing the same issue with docker image bitwarden/self-host, both on eb3e57433c7a and 8cfc531a3011. My admin dashboard looks identical to the screenshot in the original post.

Developer Tools shows this in the network tab:

![image](https://user-images.githubusercontent.com/29699594/211179986-3b4bff90-2622-46ca-af77-993c6eca7f26.png)

If I open https://mydomain/admin/home/getinstalledwebversion directly, it returns "Unable to fetch installed version", with a 500 status code.

I am also able to access version.json, which responds: { "version": "2022.12.0" }

I am using SSL though Caddy as a reverse proxy. Caddy is forwarding to 8080 on the Bitwarden container.

**Comment by delightfuleagle** [comment]
The problem is that `globalSettings__baseServiceUri__internalVault` is hard-coded to `http://localhost:80` in Dockerfile.
At [HomeController.cs](https://github.com/bitwarden/server/blob/master/src/Admin/Controllers/HomeController.cs) `requestUri = $"{_globalSettings.BaseServiceUri.InternalVault}/version.json"` is used for `GetInstalledWebVersion`.

Manually setting `globalSettings__baseServiceUri__internalVault` in your `settings.env` will fix the issue.
Maybe `entrypoint.sh` can be extended to set it automatically.

**Comment by kspearrin** [comment]
Should be fixed in the next version.

**Comment by FriderKlugser** [comment]
@kspearrin still not fixed, if used with HTTPS and Let's Encrypt Certificate. Propably because of missing "localhost" in the Subject Alternative Name (SAN).

The admin.log shows:
`fail: Bit.Admin.Controllers.HomeController[0]
      => SpanId:db8276ec2154a580, TraceId:a08743b8b4e95c5e36bc4bfb398884e5, ParentId:0000000000000000 => ConnectionId:0HMQ98BIBMHQK => RequestPath:/admin/hom
e/getinstalledwebversion RequestId:0HMQ98BIBMHQK:00000002 => Bit.Admin.Controllers.HomeController.GetInstalledWebVersion (Admin)
      Error encountered while sending GET request to https://localhost:443/version.json
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificat
eNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean
 isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, S
tream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, S
tream stream, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation 1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, Cancel
lationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts
, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Bit.Admin.Controllers.HomeController.GetInstalledWebVersion(CancellationToken cancellationToken) in /source/src/Admin/Controllers/HomeController.
cs:line 73
`

**Comment by cvondraoti** [comment]
seeing same issue with added twist on server version:

![image](https://github.com/bitwarden/server/assets/150847311/2d071915-dd7b-484a-b8be-9005be2e7be9)
