### ISSUE TITLE
Hub notifications not working

### ISSUE THREAD

**Issue by aaxdev** [bitwarden/server#895]
### Details

Hub notifications are not working on notifications.bitwarden.com. The web-vault, desktop and browser extension are able to connect to the hub, but they never receive any notifications when something has changed in vault (e.g ciphers create/update/delete..).

**Comment by kspearrin** [comment]
Please try now. this should be fixed.

**Comment by aaxdev** [comment]
It worked only for few hours, currently it's still not working.
