### ISSUE TITLE
Cannot share item and modify item at the same time

### ISSUE THREAD

**Issue by nCubed** [bitwarden/server#976]
While using the Chrome Extension, any changes made to an item while sharing an item are dropped.

**Repro Steps**

1. Edit existing item
2. Change item name (do not save, yet)
3. Share item > select collection > save
(at this point, you are now returned back to the item)
4. Save item

Actual: Item is shared, but name change is dropped.

Expected: Item is shared and the name change is committed.

**Comment by djsmith85** [comment]
Closing this issue as it appears the originally posted problem has been resolved. If this happens again or continues to be an issue please feel free to re-open this issue and let us know, along with any additional detail to assist with reproduction and root cause analysis.

**Comment by nCubed** [comment]
Looks like the option to share an item has been removed from the edit screen. Not quite resolved, more like the option has been removed during edit. Good enough :)
